[package]
name = "math-render"
version = "0.1.0"
authors = ["Manuel Reinhardt <manuel.jr16@gmail.com>"]

[dependencies]
quick-xml = "0.2.1"
#harfbuzz-sys = "0.1.5"
harfbuzz-sys = { git = "https://github.com/LifeIsHealthy/rust-harfbuzz.git" }
freetype-rs = "0.11.0"
image = "*"
interpolate_idents = "0.1.2"
svg = "0.5.1"
